title: Submarine Sailor Gifts & Milestones (to be launched soon)
author: GitHub User
email: your-email@domain.com
description: > # Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  Watch for this site to get underway with all things submarine.
  
# social links
Facebook_username: https://www.facebook.com/SubSailorGifts/
github_username:  710 Ken

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-architect
